### ISSUE TITLE
Not working on if parent has position:absolute

### ISSUE THREAD

**Issue by lollobaldo** [rwu823/react-ripples#11]
Ripple effect does not work if the container is positioned via `position:absolute;` (i.e. floating button).

The problem seems to be the positioning of the `s` ripple element, which coordinates should be relative to the parent, but are absolute of the window. I tried making it `position:fixed;` however it is now over the parent and therefore not bounded anymore

**Comment by rwu823** [comment]
Hi cloud you provide a [code sandbox](https://codesandbox.io/) demo?

**Comment by rwu823** [comment]
Discuss here #13
