### ISSUE TITLE
changing the color via props.color is not working after the initial render.

### ISSUE THREAD

**Issue by wemakeweb** [rwu823/react-ripples#12]
changing the color via `props.color` is not working after the initial render.

Suggestion: Merge `props.color` into `state.rippleStyle` inside `render` method.

**Comment by rwu823** [comment]
Not sure what you mean, but `props.color` is already in `state.rippleStyle`

https://github.com/rwu823/react-ripples/blob/master/src/createRipples.tsx#L55

**Comment by wemakeweb** [comment]
Initial it is, yes. But if you change `props.color` during the component lifetime it will not update `state.rippleStyle` .
