### ISSUE TITLE
Doesn't work if any parent is not position:static

### ISSUE THREAD

**Issue by keithpickering** [rwu823/react-ripples#13]
Love the effect, but the library is almost unusable due to this issue. Every ancestor of the <Ripple> component must be position:static, otherwise the positioning of the ripple is off. I'm guessing the click coordinates are determined based on the current positioning context rather than being relative to the whole document - if there's no known fix I might make a PR

**Comment by keithpickering** [comment]
Found a way to fix this. In createRipples.js:

First we need a function that uses getBoundingClientRect to return the relative coordinates, like so:
```
function getRelativeCoords(ev) {
  var bounds = ev.currentTarget.getBoundingClientRect();
  var x = ev.clientX - bounds.left;
  var y = ev.clientY - bounds.top;
  return {x,y};
}
```
Then in the `createRipples` function, we can just call that function on the event object and use the returned `x` and `y` values for `left` and `top` respectively. 

This seems to work perfectly, but there is a short delay. I guess the extra complexity just makes it take longer. I wonder if there's a really good way to do this effect on any element without relying on getBoundingClientRect.

**Comment by rwu823** [comment]
Hi @keithpickering 

Thanks for report and resolutions, I'll have time to research this.

**Comment by keithpickering** [comment]
Thanks for the quick fix!
