### ISSUE TITLE
Dist is requiring "React" instead of "react"

### ISSUE THREAD

**Issue by Ephys** [rwu823/react-ripples#2]
Hello,

Your build script transforms `import 'react'` intro `require("React")` (emphasis on the uppercase `R`) which causes problems when requiring this library as the app cannot find `node_modules/React` on case-sensitive filesystem (such as mine).

Do you think it would be possible to fix ? :)
Thanks in advance,

**Comment by rwu823** [comment]
It should be fixed in `v0.3.0`
https://github.com/rwu823/react-ripples/releases/tag/v0.3.0
