### ISSUE TITLE
Ripple effect on button with borderRadius.

### ISSUE THREAD

**Issue by fireflypie** [rwu823/react-ripples#9]
Buttons with a borderRadius (eg. 25px) have issues displaying the effect. Basically the button receives a background which also ripples.

**Comment by rwu823** [comment]
@fireflypie  Cloud you show me some more example code?

**Comment by rwu823** [comment]
I'm not sure I understand your situation. Actually if your child button has border radius, you can do a wrapper with `<Ripples />` by your self

```jsx
render () {
return (
  <div style={{ borderRadius: 25, overflow: 'hidden', display: 'inline-block' }}>
    <Ripples>
      <span>Click</span>
    </Ripples>
  </div>
)
}
```

**Comment by rwu823** [comment]
I created a radius button example. Just visit the new doc: https://rwu823.github.io/react-ripples/
